
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module ProjectOne(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW

);



//=======================================================
//  REG/WIRE declarations
//=======================================================
myTop(SW [9:0],HEX0 [7:0],HEX1 [7:0],HEX2 [7:0],HEX3 [7:0],HEX4 [7:0],HEX5 [7:0],LEDR [9:0],ADC_CLK_10, KEY [1:0]);



//=======================================================
//  Structural coding
//=======================================================



endmodule
